// scratch/test_browser_payload_smoke.ts
// Verifies exact browser payloads generated by ScenarioScreen against api/ai.ts POST() handler.

import fs from 'fs';
import path from 'path';
import { POST } from '../api/ai.js';
import { buildAiContext } from '../src/ai/contextBuilder';
import { createInitialSimulationState } from '../src/engine/simulationState';
import { earthquakeScenario } from '../src/data/earthquake';
import { fireScenario } from '../src/data/fire';
import { floodScenario } from '../src/data/flood';
import type { DecisionNode } from '../src/data/types';

function safeLoadEnv(): { apiKey?: string; model?: string } {
  const envPath = path.resolve(process.cwd(), '.env.local');
  if (!fs.existsSync(envPath)) return {};
  const content = fs.readFileSync(envPath, 'utf-8');
  let apiKey: string | undefined;
  let model: string | undefined;

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (trimmed.startsWith('GEMINI_API_KEY=')) {
      apiKey = trimmed.slice('GEMINI_API_KEY='.length).trim().replace(/^["']|["']$/g, '');
    }
    if (trimmed.startsWith('GEMINI_MODEL=')) {
      model = trimmed.slice('GEMINI_MODEL='.length).trim().replace(/^["']|["']$/g, '');
    }
  }
  return { apiKey, model };
}

function assert(condition: boolean, message: string): void {
  if (!condition) {
    console.error(`❌ ASSERTION FAILED: ${message}`);
    process.exit(1);
  }
}

async function runBrowserSmoke(): Promise<void> {
  console.log('🧪 Starting Browser Payload Smoke Test on /api/ai POST()...\n');
  const { apiKey, model } = safeLoadEnv();

  // Test 1: Earthquake Initial Node (with "SECONDARY HAZARD: RUPTURED GAS LINE & ELECTRICAL ARC")
  console.log('▶ [1] Testing Earthquake initial node payload (previously 400 due to "HAZARD:")...');
  const eqSim = createInitialSimulationState('earthquake');
  const eqNode = earthquakeScenario.nodes['eq-d1-shake'] as DecisionNode;
  const eqAiCtx = buildAiContext(eqSim, eqNode, 'earthquake', 'earthquake', []);

  const eqPayload = {
    action: 'narrate',
    request: {
      type: 'ENVIRONMENTAL_ATMOSPHERE',
      context: eqAiCtx,
      language: 'en',
    },
  };

  const originalKey = process.env.GEMINI_API_KEY;
  const originalModel = process.env.GEMINI_MODEL;

  try {
    if (apiKey) process.env.GEMINI_API_KEY = apiKey;
    if (model) process.env.GEMINI_MODEL = model;

    const req1 = new Request('http://localhost:3000/api/ai', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(eqPayload),
    });

    const res1 = await POST(req1);
    assert(res1.status === 200, `Expected 200, got HTTP ${res1.status}`);
    const body1 = (await res1.json()) as any;
    assert(body1.payload && typeof body1.payload.text === 'string', 'Expected valid narrative text');
    console.log(`  ✓ Earthquake request succeeded (status: ${res1.status}, source: ${body1.source})`);
    console.log(`  Narrative: "${body1.payload.text}"`);

    // Test 2: Fire Window Node (previously 400 due to "window")
    console.log('\n▶ [2] Testing Fire window-signal node payload (previously 400 due to "window")...');
    const fireSim = createInitialSimulationState('fire');
    const fireNode = fireScenario.nodes['fire-d4b-window-signal'] as DecisionNode;
    const fireAiCtx = buildAiContext(fireSim, fireNode, 'fire', 'fire', [
      { nodeId: 'fire-d1-alarm', choiceLabel: 'Investigate window', isCorrect: true },
    ]);

    const firePayload = {
      action: 'narrate',
      request: {
        type: 'ENVIRONMENTAL_ATMOSPHERE',
        context: fireAiCtx,
        language: 'hinglish',
      },
    };

    const req2 = new Request('http://localhost:3000/api/ai', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(firePayload),
    });

    const res2 = await POST(req2);
    assert(res2.status === 200, `Expected 200, got HTTP ${res2.status}`);
    const body2 = (await res2.json()) as any;
    assert(body2.payload && typeof body2.payload.text === 'string', 'Expected valid narrative text');
    assert(!/[\u0900-\u097F]/.test(body2.payload.text), 'Hinglish must be Roman script');
    console.log(`  ✓ Fire window request succeeded (status: ${res2.status}, source: ${body2.source})`);
    console.log(`  Narrative: "${body2.payload.text}"`);

    // Test 3: Flood Street Node in Fallback Mode (unconfigured)
    console.log('\n▶ [3] Testing Flood scenario in deterministic fallback mode...');
    delete process.env.GEMINI_API_KEY;

    const floodSim = createInitialSimulationState('flood');
    const floodNode = floodScenario.nodes['flood-d1-warning'] as DecisionNode;
    const floodAiCtx = buildAiContext(floodSim, floodNode, 'flood', 'flood', []);

    const floodPayload = {
      action: 'narrate',
      request: {
        type: 'ENVIRONMENTAL_ATMOSPHERE',
        context: floodAiCtx,
        language: 'en',
      },
    };

    const req3 = new Request('http://localhost:3000/api/ai', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(floodPayload),
    });

    const res3 = await POST(req3);
    assert(res3.status === 200, `Expected 200, got HTTP ${res3.status}`);
    const body3 = (await res3.json()) as any;
    assert(body3.deterministicFallbackUsed === true, 'Fallback should be true');
    assert(body3.source === 'deterministic-fallback', 'Source should be deterministic-fallback');
    console.log(`  ✓ Flood fallback succeeded (status: ${res3.status}, source: ${body3.source})`);

    // Test 4: Secret Leakage Check
    console.log('\n▶ [4] Checking response bodies for secret exposure...');
    if (apiKey) {
      assert(!JSON.stringify(body1).includes(apiKey), 'Key must not be in body1');
      assert(!JSON.stringify(body2).includes(apiKey), 'Key must not be in body2');
      assert(!JSON.stringify(body3).includes(apiKey), 'Key must not be in body3');
      console.log('  ✓ No API keys exposed.');
    }

    console.log('\n🎉 ALL BROWSER PAYLOAD SMOKE TESTS PASSED WITH HTTP 200!');
  } finally {
    process.env.GEMINI_API_KEY = originalKey;
    process.env.GEMINI_MODEL = originalModel;
  }
}

runBrowserSmoke().catch((err) => {
  console.error('Fatal test error:', err);
  process.exit(1);
});
